$hyprlockDir = $HOME/.config/hyprlock

# Script Path
$music = $hyprlockDir/scripts/playerctlock.sh
$album = $hyprlockDir/scripts/hlock_mpris.sh
$weather = $hyprlockDir/scripts/weather.sh

source = $hyprlockDir/layouts/mylayout/mylayout.conf
