$hyprlockDir = ~/.config/hyprlock
$openweather_key = ""
$city = 

# Script Path
$music = $hyprlockDir/scripts/playerctlock.sh
$album = $hyprlockDir/scripts/hlock_mpris.sh
$weather = $hyprlockDir/scripts/weather.sh

# Devices
$monitor1 =  # for resolution 2560x1440
$monitor2 =  # for resolution 1920x1080
$keyboard = "" # for exaple: "leku-nut65-2.4g-wireless-keyboard" 

source = $hyprlockDir/layouts/mylayout/mylayout.conf
