[Preprocesses]
disable_sentry     = 1
disable_ui_logging = 1
remove_rtl_rule    = 1
expose_apis        = 1

[AdditionalOptions]
custom_apps           = marketplace
sidebar_config        = 0
home_config           = 1
experimental_features = 1
extensions            = transparent.js

[Patch]

[Setting]
overwrite_assets       = 1
check_spicetify_update = 1
current_theme          = Hazy
color_scheme           = Coral
replace_colors         = 1
spotify_launch_flags   = 
always_enable_devtools = 0
spotify_path           = /opt/spotify/
prefs_path             = /home/kn1ver/.config/spotify/prefs
inject_theme_js        = 1
inject_css             = 1

; DO NOT CHANGE!
[Backup]
version = 1.2.82.428.g0ac8be2b
with    = 2.42.12
