# If your monitors have diffrent resolutions you may need to change positions of some elemets
# Here are only posotions for 2560x1440 (monitor1) and 1920x1080 (monitor2)
$monitor1 = DP-3
$monitor2 = HDMI-A-1

# Music Album Art
image {
    monitor =
    path = $mpris_art
    size = 110
    rounding = 20
    rotate = 0
    reload_time = 0
    reload_cmd = 
    position = -45, -410
    halign = center
    valign = center
    zindex = 5
}

# Player Source
label {
    monitor =
    text = cmd[update:1000] echo "$($music --source)"  | awk '{print $1}'
    color = rgba(255, 255, 255, 0.6)
    font_size = 10
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = -275, -360
    halign = center
    valign = center
    zindex = 5
}

# Player Source Icon
label {
    monitor =
    text = cmd[update:1000] echo "$($music --source)"  | awk '{print $2}'
    color = rgba(255, 255, 255, 0.6)
    font_size = 16
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = -235, -360
    halign = center
    valign = center
    zindex = 5
}

# Title
label {
    monitor = $monitor1
    text = cmd[update:1000] echo "$($music --title)"
    color = rgba(255, 255, 255, 0.8)
    font_size = 12
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 970, -400
    halign = left
    valign = center
    zindex = 5
}

# Artist
label {
    monitor = $monitor1
    text = cmd[update:1000] echo "$($music --artist)"
    color = rgba(255, 255, 255, 0.8)
    font_size = 10
    font_family = JetBrains Mono Nerd Font Mon440, 110o ExtraBold
    position = 970, -425 # center: -275, -425
    halign = left
    valign = center
    zindex = 5
}

# Player Status
label {
    monitor =
    text = cmd[update:1000] echo "$($music --status)"
    onclick = playerctl -p spotify play-pause
    color = rgba(255, 255, 255, 1)
    font_size = 21
    font_family = JetBrains Mono Nerd Font Mono 
    position = -210, -455
    halign = center
    valign = center
    zindex = 5
}

# Step Forward
label {
    monitor =
    text = 
    onclick = playerctl -p spotify next
    color = rgb(255, 255, 255)
    font_size = 15
    position = -180, -455.25
    halign = center
    valign = center
    zindex = 5
}

# Step Backward
label {
    monitor =
    text = 
    onclick = playerctl -p spotify previous
    color = rgb(255, 255, 255)
    font_size = 15
    position = -240, -455.25
    halign = center
    valign = center
    zindex = 5
}


# ===================================== Doubling for $monitor2 Monitor =====================================

# Artist
label {
    monitor = $monitor2
    text = cmd[update:1000] echo "$($music --artist)"
    color = rgba(255, 255, 255, 0.8)
    font_size = 10
    font_family = JetBrains Mono Nerd Font Mon440, 110o ExtraBold
    position = 650, -425 # center: -275, -425
    halign = left
    valign = center
    zindex = 5
}

# Title
label {
    monitor = $monitor2
    text = cmd[update:1000] echo "$($music --title)"
    color = rgba(255, 255, 255, 0.8)
    font_size = 12
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 650, -400
    halign = left
    valign = center
    zindex = 5
}
