$keyboard = "leku-nut65-2.4g-wireless-keyboard"

label {
    monitor =
    text = 
    color = rgb(255, 255, 255)
    onclick = poweroff
    font_size = 24
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 280, 360
    halign = center
    valign = center
    zindex = 1
}

label {
    monitor =
    text = 󰜉
    color = rgb(255, 255, 255)
    onclick = reboot
    font_size = 24
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 220, 360
    halign = center
    valign = center
    zindex = 1
}

label {
    monitor =
    text = cmd[update:500] ~/.config/hyprlock/scripts/lang_layout.sh
    onclick = hyprctl switchxkblayout $keyboard next
    color = rgb(255, 255, 255)
    font_size = 12
    font_family = Ubuntu Bold
    position = 160, 360
    halign = center
    valign = center
}
